In [1]:
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d.shape
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [3]:
arr2d[2]

array([7, 8, 9])

In [4]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
#統計使用實用方法
arr = np.random.randint(50,101,size=(10,5))
arr.sum()
arr.sum(0)
arr.sum(axis=1)

array([360, 343, 381, 310, 369, 348, 359, 368, 355, 382])

In [9]:
#使用numpy內的function
arr = np.random.randint(50,101,size=(10,5))
np.sum(arr)
np.sum(arr,axis=0)
np.sum(arr,axis=1)

array([350, 396, 358, 413, 343, 393, 381, 328, 428, 374])

In [ ]:
#常用的統計方法
#sum
#mean
#std
#max
#min
#median